apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: bwk8s-datafortress-cloud-tls
spec:
  secretName: bwk8s-datafortress-cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bwk8s-datafortress-cloud
  dnsNames:
    - bwk8s-datafortress-cloud
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bwk8s-datafortress-cloud