apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flask
  template:
    metadata:
      labels:
        component: flask
    spec:
      containers:
        - name: carflask
          # VERSION will be replaced by sed in travis 
          image: guestros/carflask:VERSION
          ports:
            - containerPort: 5000
          env:
            - name: DBHOST
              value: postgres-clusterip-service
            - name: DBUSER
              value: postgres
            - name: DBNAME
              value: cardb
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD